### ISSUE TITLE
Ecommerce permissions 

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-ecommerce#19]
It's possible hide e-commerce menu for roles?

![screen shot 2016-02-05 at 11 39 29](https://cloud.githubusercontent.com/assets/2389019/12845370/2ccec034-cbfd-11e5-8d85-b5e511d60d31.png)

Regards!

**Comment by owen2345** [comment]
Fixed!

**Comment by raulanatol** [comment]
Works perfect! Thx!
