### ISSUE TITLE
Taxes per product

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-ecommerce#22]
Hi!

Somebody uses the taxes per product?
I'm thinking to change this feature. 
In WooCommerce for example, the taxes are calculated for country, state... see the screenshot.

![c26z](https://cloud.githubusercontent.com/assets/2389019/13462847/5cb5e64a-e081-11e5-9928-12cca99c37e1.png)

Are there any objections?
Regards.

**Comment by mazharoddin** [comment]
Yes, taxes per product along with global tax rates is helpful.

**Comment by raulanatol** [comment]
But taxes It's not for country?
How do you use taxes for product?
Could you give me an example?

I have a problem with this feature because if I put a taxes for product I can't change this for each country, city...

For example:
**Item1** 
Price: $10
Tax: 1%

Client from New York - Taxes must be 4.375%
Client from US CA - Taxes must be 2%

**Comment by mazharoddin** [comment]
Yes, usually taxes are per country , but in India we have different taxes for states within country, also taxes differ based on product type e.g baby products tax rates are different from medical related products.

**Comment by raulanatol** [comment]
Ok!
I think that the best option is create a tax product class like magento.
https://www.packtpub.com/books/content/creating-tax-rules-magento
http://www.appseconnect.com/creating-tax-rules-in-magento/

In this case @mazharoddin.
What would the calculation?

**Item 1**
Baby product tax rate: 2%
Price: $10

**Item 2**
No tax product class
Price: $20

User from NYC with Country tax (4%)

[Case A] The checkout value:  ($10 \* 1.02) + ($20 \* 1.04) =  $31 (total with taxes)
[Case B] The checkout value:  (($10 \* 1.02) + $20) \* 1.04) =  $31,408 (total with taxes)

**Comment by mazharoddin** [comment]
Yes, that helps. But  keeping it simple like  bigcartel may be more helpful.
![screen shot 2016-03-03 at 14 40 03](https://cloud.githubusercontent.com/assets/6102465/13489605/fdb74fa8-e14d-11e5-905c-573d5e479f91.png)

**Comment by raulanatol** [comment]
Ok @mazharoddin I will work in this.
Regards.
