### ISSUE TITLE
Having different prices for different attributes for the same product

### ISSUE THREAD

**Issue by rroveri** [owen2345/camaleon-ecommerce#24]
It would be useful to have different prices for different versions of the same product (red, green, blue, ...)

**Comment by owen2345** [comment]
Hi @rroveri  Good idea!

**Comment by mazharoddin** [comment]
Hi @owen2345, 

Yeah its nice to have variants, but while implementing this feature if possible refer to Shopify implementation once, adding variants can be very confusing if its not properly implemented. 
I am attaching few screen shots from Shopify create product page.

![screen shot 2016-06-16 at 18 46 10](https://cloud.githubusercontent.com/assets/6102465/16118078/f65887ac-33f2-11e6-81b8-c39e89fd09d2.png)
![screen shot 2016-06-16 at 18 46 50](https://cloud.githubusercontent.com/assets/6102465/16118079/f7738a9c-33f2-11e6-8e93-bd84c9dab175.png)
![screen shot 2016-06-16 at 18 49 20](https://cloud.githubusercontent.com/assets/6102465/16118097/1187db7c-33f3-11e6-8c87-004daef3b27b.png)

Also please note that only Shopify automatically creates SKUs for variants, really its useful feature to have SKUs get created automatically for variants, otherwise it would be confusing for users.
Also pls  plan to upload individual image upload for variants, so that each variant has different image, if there are no images uploaded then it will show from main product.
![screen shot 2016-06-16 at 19 00 31](https://cloud.githubusercontent.com/assets/6102465/16118489/e82cef2c-33f4-11e6-99ad-dc2e05e003fe.png)
![screen shot 2016-06-16 at 19 01 02](https://cloud.githubusercontent.com/assets/6102465/16118491/e9d0afe4-33f4-11e6-84d4-04713d991ec0.png)

**Comment by owen2345** [comment]
@mazharoddin it appears complex hehe!

**Comment by mazharoddin** [comment]
@oweb2345, for you it won't be complex :)

**Comment by owen2345** [comment]
but, I was looking for some job to get some money, because I was fulltime with Camaleon without getting money. hehe!

**Comment by mazharoddin** [comment]
@owen2345 , true ...money also important factor..I agree ...
Whenever you feel or try to implement ..then consider shopify implementation, otherwise it may be really confusing ..now even without this option product pages are useful, atleast they are not complex.

**Comment by owen2345** [comment]
Hi @mazharoddin 
I added the product variations, could you please test it?

Regards,

**Comment by mazharoddin** [comment]
Sure @owen2345...Thanks

**Comment by mazharoddin** [comment]
Hi @owen2345, I am unable to test, I am getting below error while trying to add variant image.

```
Completed 500 Internal Server Error in 180ms (ActiveRecord: 3.8ms)

MiniMagick::Error (`mogrify -resize nullx /var/folders/kc/y4gc2tps1pxdv5ty4n4syjp80000gn/T/mini_magick20160709-13273-eqaa99.jpg` failed with error:
mogrify: invalid argument for option `nullx': -resize @ error/mogrify.c/MogrifyImageCommand/5799.
):
  mini_magick (4.5.1) lib/mini_magick/shell.rb:18:in `run'
  mini_magick (4.5.1) lib/mini_magick/tool.rb:92:in `call'
  mini_magick (4.5.1) lib/mini_magick/tool.rb:40:in `new'
  mini_magick (4.5.1) lib/mini_magick/image.rb:504:in `mogrify'
  mini_magick (4.5.1) lib/mini_magick/image.rb:384:in `combine_options'
  /Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-55fcf12d0190/app/helpers/camaleon_cms/uploader_helper.rb:145:in `cama_crop_image'
  /Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-55fcf12d0190/app/helpers/camaleon_cms/uploader_helper.rb:245:in `cama_resize_upload'
  /Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-55fcf12d0190/app/helpers/camaleon_cms/uploader_helper.rb:39:in `upload_file'
  /Users/mazharoddin/.rvm/gems/ruby-2.2.2@rails4.2.5/bundler/gems/camaleon-cms-55fcf12d0190/app/controllers/camaleon_cms/admin/media_controller.rb:79:in `upload'
```

I tried to update ImageMagick on my Mac, but I already have latest version,

```
brew upgrade ImageMagick
Error: imagemagick 6.9.2-7 already installed
```

**Comment by mazharoddin** [comment]
hi @owen2345,
I am getting below error if I try to add a product without variants.

```
undefined method `keys' for nil:NilClass
Extracted source (around line #79):
  def ecommerce_admin_product_created(args)
    if args[:post_type].slug == 'commerce'
      args[:post].product_variations.where.not(id: params[:product_variation].keys).delete_all
      params[:product_variation].each do |p_key, p_var|
        data = {amount: p_var[:price], photo: p_var[:photo], sku: p_var[:sku], weight: p_var[:weight], qty: p_var[:qty], attribute_ids: p_var[:attributes].map{|at| at[:value] }.join(',')}
        if p_key.include?('new_') # new variation


vendor/plugins/camaleon-ecommerce/app/helpers/plugins/ecommerce/ecommerce_helper.rb:79:in `ecommerce_admin_product_created'
```

Here is the repository details.

```
github.com:mazharoddin/camaleon_cms_debug.git
```

-Thanks.

**Comment by owen2345** [comment]
@mazharoddin  Fixed variations!
I tried many times to reproduce the imagemagick problem, but without success.

**Comment by mazharoddin** [comment]
Sure np, Let me re-try. Thanks.

**Comment by mazharoddin** [comment]
@owen2345 ,

Now I am able to create product with variants.
But I am getting below error if I try to create a variant without adding product attributes.

```
undefined method `map' for nil:NilClass
      args[:post].product_variations.where.not(id: params[:product_variation].keys).delete_all
      params[:product_variation].each do |p_key, p_var|
        data = {amount: p_var[:price], photo: p_var[:photo], sku: p_var[:sku], weight: p_var[:weight], qty: p_var[:qty], attribute_ids: p_var[:attributes].map{|at| at[:value] }.join(',')}
        if p_key.include?('new_') # new variation
          args[:post].product_variations.create(data)
        else
vendor/plugins/camaleon-ecommerce/app/helpers/plugins/ecommerce/ecommerce_helper.rb:82:in `block in ecommerce_admin_product_created'
actionpack (4.2.6) lib/action_controller/metal/strong_parameters.rb:185:in `each_pair'
```

Can you please create some default 'Product Attributes' whenever user activates eCommerce plugin.

Color, Size and material etc attributes are  commonly used, these can be created by default.
What do you think.

Imagemagick error I am getting only with variants images, normal product image upload is working fine with out any issue.
I am unable to insert existing images in variants.

![screen shot 2016-07-12 at 18 07 57](https://cloud.githubusercontent.com/assets/6102465/16767136/991cad16-485b-11e6-8ace-c5422d7c414c.png)

If I try to upload new image I am getting this error.

![screen shot 2016-07-12 at 18 09 34](https://cloud.githubusercontent.com/assets/6102465/16767182/d232ed0e-485b-11e6-97d6-26bc55f4e0c9.png)

```
Completed 500 Internal Server Error in 86ms (ActiveRecord: 1.1ms)

MiniMagick::Error (`mogrify -resize nullx /var/folders/kc/y4gc2tps1pxdv5ty4n4syjp80000gn/T/mini_magick20160712-30646-idd5h3.jpg` failed with error:
mogrify: invalid argument for option `nullx': -resize @ error/mogrify.c/MogrifyImageCommand/5799.
):
  mini_magick (4.5.1) lib/mini_magick/shell.rb:18:in `run'
```

**Comment by owen2345** [comment]
Fixed!
The problem was a null value sent from js

**Comment by mazharoddin** [comment]
Thanks @owen2345, let me check if its working.

**Comment by mazharoddin** [comment]
Hi @owen2345, 
I am able to crop the images now, but dimensions are  not getting updated if I use cloudfront/S3 images, so am unable to insert image( insert option is blank).
<img width="309" alt="screen shot 2016-07-27 at 08 53 20" src="https://cloud.githubusercontent.com/assets/6102465/17162966/6161b758-53d8-11e6-9666-09564475e7ec.png">

**Comment by owen2345** [comment]
Fixed image insert

**Comment by mazharoddin** [comment]
Thanks @owen2345
