### ISSUE TITLE
PayU.in payment GW support

### ISSUE THREAD

**Issue by mazharoddin** [owen2345/camaleon-ecommerce#27]
Hi @owen2345, 
Can you please provide PayU.in payment gateway support during checkout, currently this is only free payment gateway for Indian customers, it would be great help if you can add support for PayU.in, since we can't use paypal, stripe etc payment Gateways.
Here is the official repository of PayU.in.
git@github.com:payu-india/PayU-Integration-Kit-ROR.git

**Comment by owen2345** [comment]
I added hooks to add custom payment methods:
https://github.com/owen2345/camaleon-ecommerce/blob/master/app/helpers/plugins/ecommerce/ecommerce_functions_helper.rb#L53

**Comment by mazharoddin** [comment]
@owen2345, Thank you!!
