### ISSUE TITLE
Migrations destroy data

### ISSUE THREAD

**Issue by p-decoraid** [owen2345/camaleon-ecommerce#29]
Looking at this migration:

https://github.com/owen2345/camaleon-ecommerce/blob/master/db/migrate/20160527184747_add_new_cart_structure.rb

The data in the `plugins_order_details` table is simply deleted which is not good because we have real orders.

**Comment by owen2345** [comment]
OOOOPs I forget to add the migration of current data into new structure before destroy the table.
Could you please do it?
Regards,

**Comment by p-decoraid** [comment]
I suppose I don't have much choice in the matter. For reference, this was done in 189584d4.

**Comment by p-decoraid** [comment]
@owen2345 it looks like the phone number is no longer part of the order information, meaning if a user changes their phone number all orders they have previously placed would show the newly entered phone number. Is this intentional?

**Comment by p-decoraid** [comment]
Billing address does not have a phone number either. Including a phone number in both shipping and billing addresses seems like a standard practice these days.

**Comment by owen2345** [comment]
Also, added phone numbers for shipping and billing addresses.

**Comment by p-decoraid** [comment]
Thanks!
