### ISSUE TITLE
Plugin to gem

### ISSUE THREAD

**Issue by raulanatol** [owen2345/camaleon-ecommerce#4]
Hi!

They plans to make changes in the plugin to become a gem plugin?

Regards.

**Comment by owen2345** [comment]
Hi,
Next week I will convert this plugin into gem version.

**Comment by raulanatol** [comment]
Thx! @owen2345 

I have a lot of work but if you want I can do it. 
So you can do other things more important

**Comment by owen2345** [comment]
great, thanks a lot Raul.

**Comment by raulanatol** [comment]
I have created a pull request: https://github.com/owen2345/camaleon-ecommerce/pull/5
